before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
    ldflags:
      - -s -w
      - -X github.com/drzero42/vk/cmd.version={{.Version}} -X github.com/drzero42/vk/cmd.commit={{.ShortCommit}} -X github.com/drzero42/vk/cmd.date={{.Date}}
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
